CXX=		g++
CXXFLAGS=	-g -Wall -std=gnu++11
SHELL=		bash
PROGRAMS=	worddice

all:		worddice

worddice:	worddice.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^

generate_map: src/generate_map.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^

.PHONY:		test test-output test-memory clean

clean:
	rm -f $(PROGRAMS)
